import { Button, Text, View } from 'react-native';
import { router } from 'expo-router';

export default function LiveAlertsScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', padding: 20, gap: 12 }}>
      <Text style={{ fontSize: 24 }}>Live Alerts</Text>
      <Text>Review active alerts generated by your dog's device.</Text>
      <Button title="Go to Alert Details" onPress={() => router.push('/(tabs)/home/alert-details')} />
    </View>
  );
}
